spring:
  data:
    mongodb:
      database: employee-db
      uri: mongodb://localhost:27017/employee-db

  main:
    web-application-type: reactive

server:
  port: 8080

external:
  service:
    base-url: http://localhost:8081/departments
